### ISSUE TITLE
code switch变量解释

### ISSUE THREAD

**Issue by jiay7** [jctian98/e2e_lfmmi#11]
非常有用的code-switch的工作！我有一个小小的疑问：

https://github.com/jctian98/e2e_lfmmi/blob/34b8056906631c6282bd2f0320764d645c33ca0d/nets/pytorch_backend/e2e_asr_transducer_cs.py#L346

ys_pad, cls_ids = ys_pad[:, 1:], ys_pad[:, 0].squeeze(0)
这里的cls_ids是用的全局的language id作为label吗？分三类：中文、英文、中英混？

**Comment by jctian98** [comment]
I'll answer in English so other people may also understand this.

Yes, the `cls_ids` is exactly the language id.  Please refer these lines: https://github.com/jctian98/e2e_lfmmi/blob/34b8056906631c6282bd2f0320764d645c33ca0d/nets/pytorch_backend/e2e_asr_transducer_cs.py#L203-L205

**Comment by jiay7** [comment]
Thank you for your reply.

Another question.  The parameter is named self.use_adversial_examples (https://github.com/jctian98/e2e_lfmmi/blob/34b8056906631c6282bd2f0320764d645c33ca0d/nets/pytorch_backend/e2e_asr_transducer_cs.py#L390) is false by default, indicating that <man> and <eng> are not involved in CTC loss calculation as ordinary labels. Still, the reference paper indicates that <man> and <eng> are involved in CTC loss calculation as ordinary labels.

**Comment by jctian98** [comment]
Please refer to the code below:

https://github.com/jctian98/e2e_lfmmi/blob/34b8056906631c6282bd2f0320764d645c33ca0d/nets/pytorch_backend/e2e_asr_transducer_cs.py#L390-L396

If  `use_adversial_examples` is set to `False`, the CTC loss for the mandarin-specific decoder will only be computed for the Mandarin and CS utterances; otherwise, it will be computed for any utterance (even the training label for the English utterances are all `<Eng>`). 

By default, I would recommend you set this to `True`
