### ISSUE TITLE
about SOTA

### ISSUE THREAD

**Issue by SSRDMP** [jctian98/e2e_lfmmi#9]
hello jctian98
Impressive work! 
Very happy to see that aishell's sota has been refreshed again.
I have some doubts, hope you can help me figure it out,
Why the aishell-1 result on paper with code leaderboard is 4.18%
https://paperswithcode.com/sota/speech-recognition-on-aishell-1
but the result on aishell-1 in you paper is, 4.10%,
Is there any different between two result?
Is the dev set used during training?
Sincerely hope to get your reply.

**Comment by jctian98** [comment]
Sorry for this late reply.
1. The 4.18% result is reported in this [paper](https://ieeexplore.ieee.org/document/9721084) and the 4.10% result is reported in this [paper](https://arxiv.org/abs/2203.15614). 
2. The CER is reduced from 4.18% to 4.10% since we have changed the training process of word-level N-gram LM. The smoothing methods for the N-gram LM do have some impact on the final CER. We find the Witten-Bell discounting is the best choice in Aishell-1 experiments. You can see [this](https://github.com/jctian98/e2e_lfmmi/blob/34b8056906631c6282bd2f0320764d645c33ca0d/egs/aishell1/prepare.sh#L234-L239) in our script to check more details about the LM training`.
3.  The dev set is used during training only for validation. We average the last 10 checkpoints for evaluation so there should be no information leak.  

Best,
Jinchuan

**Comment by SSRDMP** [comment]
> Sorry for this late reply.
> 
> 1. The 4.18% result is reported in this [paper](https://ieeexplore.ieee.org/document/9721084) and the 4.10% result is reported in this [paper](https://arxiv.org/abs/2203.15614).
> 2. The CER is reduced from 4.18% to 4.10% since we have changed the training process of word-level N-gram LM. The smoothing methods for the N-gram LM do have some impact on the final CER. We find the Witten-Bell discounting is the best choice in Aishell-1 experiments. You can see [this](https://github.com/jctian98/e2e_lfmmi/blob/34b8056906631c6282bd2f0320764d645c33ca0d/egs/aishell1/prepare.sh#L234-L239) in our script to check more details about the LM training`.
> 3. The dev set is used during training only for validation. We average the last 10 checkpoints for evaluation so there should be no information leak.
> 
> Best, Jinchuan

Thank you very much, your answer completely solved my doubts, this method is really efficient. Thanks again！
